version: '3.8'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: p-3a-image
    container_name: p-3a-container
    ports:
      - "5003:5000"
    volumes:
      - .:/app
    environment:
      FLASK_DEBUG: 1
